#
# database configuration
#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pizza_store
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

#
#  security configuration
#
security:
  configuration:
    secret-jwt: qwerty-123456
    permission:
      all:
        - /login
        - /orders
        - /orders/**
        - /test/**
        - /camunda/**
        - /engine-rest/**
        - /api/internal/**
      receptionist:
        - /receptionist/**
      chef:
        - /chef/**
      delivery:
        - /delivery/**

#
#  camunda configuration
#
camunda.bpm.admin-user:
  id: demo
  password: demo
